### ISSUE TITLE
Crash in verbs provider using FI_INJECT

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#1349]
I'm seeing the following crash running an updated version of fabtests:

#0  0x00007ffff7d97f0b in fi_ibv_send_iov_flags (ep=0x60f1a0, 
    wr=0x7fffffffe360, iov=0x7fffffffe430, desc=<value optimized out>, count=1, 
    context=0x0, flags=167772160) at prov/verbs/src/fi_verbs.c:1332
#1  0x00007ffff7d98061 in fi_ibv_msg_ep_sendmsg (ep_fid=<value optimized out>, 
    msg=<value optimized out>, flags=<value optimized out>)
    at prov/verbs/src/fi_verbs.c:1362
#2  0x0000000000403678 in fi_sendmsg ()
    at /usr/local/include/rdma/fi_endpoint.h:284
#3  ft_finalize () at common/shared.c:865
#4  0x000000000040189f in run (argc=<value optimized out>, 
    argv=<value optimized out>) at pingpong/msg_pingpong.c:194
#5  main (argc=<value optimized out>, argv=<value optimized out>)
    at pingpong/msg_pingpong.c:234

I believe that the issue is fi_ibv_set_sge_iov() is dereferencing desc, which is set to NULL since the FI_INJECT flag is set.

**Comment by shefty** [comment]
@a-ilango
