### ISSUE TITLE
prov/verbs - Assertion `buf_region->num_used == 0' failed.

### ISSUE THREAD

**Issue by fzago-cray** [ofiwg/libfabric#3351]
When running:
    # while true; do sleep 3; MPIR_CVAR_OFI_USE_PROVIDER="verbs" srun --kill-on-bad-exit -N 32 -n 256 sh -c "ulimit -c unlimited ; ./mpi/collective/osu_alltoall -m 8" ; done

I got:
    osu_alltoall: prov/util/src/util_buf.c:162: util_buf_pool_destroy: Assertion `buf_region->num_used == 0' failed.

This is quickly easily reproducible.
libfabric has to be compiled with --enable-debug.

gdb shows:
    (gdb) bt
    #0  0x00007ffff709b5f7 in raise () from /lib64/libc.so.6
    #1  0x00007ffff709cce8 in abort () from /lib64/libc.so.6
    #2  0x00007ffff7094566 in __assert_fail_base () from /lib64/libc.so.6
    #3  0x00007ffff7094612 in __assert_fail () from /lib64/libc.so.6
    #4  0x00007ffff6db0c90 in util_buf_pool_destroy (pool=0x6f0450) at prov/util/src/util_buf.c:162
    #5  0x00007ffff6df6f2c in fi_ibv_rdm_ep_close (fid=0x6effd0) at prov/verbs/src/ep_rdm/verbs_ep_rdm.c:496
    #6  0x00007ffff75c863c in MPID_nem_ofi_finalize () from /home/users/fzago/install/lib/libmpi.so.0
    #7  0x00007ffff75c3531 in MPID_nem_finalize () from /home/users/fzago/install/lib/libmpi.so.0
    #8  0x00007ffff75b6c62 in MPIDI_CH3_Finalize () from /home/users/fzago/install/lib/libmpi.so.0
    #9  0x00007ffff75a6a95 in MPID_Finalize () from /home/users/fzago/install/lib/libmpi.so.0
    #10 0x00007ffff74dec9c in PMPI_Finalize () from /home/users/fzago/install/lib/libmpi.so.0
    #11 0x000000000040126d in main (argc=3, argv=0x7fffffffd648) at osu_reduce.c:72
    (gdb) 
    #4  0x00007ffff6db0c90 in util_buf_pool_destroy (pool=0x6f0450) at prov/util/src/util_buf.c:162
162			assert(buf_region->num_used == 0);
    (gdb) p *buf_region 
    $2 = {entry = {next = 0x0}, mem_region = 0x8f5400 "@i\222", context = 0x0, num_used = 1}

**Comment by fzago-cray** [comment]
#3392 appears to fix that one.
