### ISSUE TITLE
prov/sockets Memory leaks in util_buf_grow

### ISSUE THREAD

**Issue by soumagne** [ofiwg/libfabric#4527]
I started to see recently memory leaks (using master) coming from the sockets provider, here is the backtrace:
```
Direct leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7f5897bd8c40 in realloc (/lib64/libasan.so.4+0xdec40)
    #1 0x7f589609e0d0 in util_buf_grow prov/util/src/util_buf.c:110
    #2 0x7f589609e430 in util_buf_pool_create_attr prov/util/src/util_buf.c:183
    #3 0x7f589609e53f in util_buf_pool_create_ex prov/util/src/util_buf.c:212
    #4 0x7f58960bf08b in util_buf_pool_create include/ofi_mem.h:329
    #5 0x7f58960c8b82 in sock_pe_init prov/sockets/src/sock_progress.c:2709
    #6 0x7f58960a771d in sock_domain prov/sockets/src/sock_dom.c:317
    #7 0x7f5896e05a21 in fi_domain /opt/libfabric/git/include/rdma/fi_domain.h:231
    #8 0x7f5896e0a36e in na_ofi_domain_open /home/jsoumagne/workspace/mercury/source/src/na/na_ofi.c:1788
    #9 0x7f5896e11998 in na_ofi_initialize /home/jsoumagne/workspace/mercury/source/src/na/na_ofi.c:3280
    #10 0x7f5896de0a5e in NA_Initialize_opt /home/jsoumagne/workspace/mercury/source/src/na/na.c:377
    #11 0x4110ca in NA_Test_init /home/jsoumagne/workspace/mercury/source/Testing/na/na_test.c:416
    #12 0x407b6a in HG_Test_init /home/jsoumagne/workspace/mercury/source/Testing/mercury_test.c:352
    #13 0x404622 in main /home/jsoumagne/workspace/mercury/source/Testing/test_server.c:89
    #14 0x7f589582afe9 in __libc_start_main (/lib64/libc.so.6+0x20fe9)

Direct leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7f5897bd8c40 in realloc (/lib64/libasan.so.4+0xdec40)
    #1 0x7f589609e0d0 in util_buf_grow prov/util/src/util_buf.c:110
    #2 0x7f589609e430 in util_buf_pool_create_attr prov/util/src/util_buf.c:183
    #3 0x7f589609e53f in util_buf_pool_create_ex prov/util/src/util_buf.c:212
    #4 0x7f58960bf08b in util_buf_pool_create include/ofi_mem.h:329
    #5 0x7f58960c8afa in sock_pe_init prov/sockets/src/sock_progress.c:2701
    #6 0x7f58960a771d in sock_domain prov/sockets/src/sock_dom.c:317
    #7 0x7f5896e05a21 in fi_domain /opt/libfabric/git/include/rdma/fi_domain.h:231
    #8 0x7f5896e0a36e in na_ofi_domain_open /home/jsoumagne/workspace/mercury/source/src/na/na_ofi.c:1788
    #9 0x7f5896e11998 in na_ofi_initialize /home/jsoumagne/workspace/mercury/source/src/na/na_ofi.c:3280
    #10 0x7f5896de0a5e in NA_Initialize_opt /home/jsoumagne/workspace/mercury/source/src/na/na.c:377
    #11 0x4110ca in NA_Test_init /home/jsoumagne/workspace/mercury/source/Testing/na/na_test.c:416
    #12 0x407b6a in HG_Test_init /home/jsoumagne/workspace/mercury/source/Testing/mercury_test.c:352
    #13 0x404622 in main /home/jsoumagne/workspace/mercury/source/Testing/test_server.c:89
    #14 0x7f589582afe9 in __libc_start_main (/lib64/libc.so.6+0x20fe9)
```

**Comment by soumagne** [comment]
Fixed after #4537 was merged.
