### ISSUE TITLE
prov/verbs: ubertest hangs at end of tests

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#5353]
The following backtrace is showing a hang in the async thread.  The main thread is hung in pthread_join() waiting for this thread to exit.
```
#0  0x00007ffff6a9bd13 in epoll_wait () from /lib64/libc.so.6
#1  0x00007ffff7a4e211 in fi_ibv_eq_read_internal (eq_fid=0x6647d0, timeout=-1, event=0x7ffff56dbe68,
    buf=0x7ffff56dbea8, len=40, flags=0) at prov/verbs/src/verbs_eq.c:980
#2  0x00007ffff7a4e2e4 in fi_ibv_eq_sread (eq_fid=0x6647d0, event=0x7ffff56dbe68, buf=0x7ffff56dbea8, len=40,
    timeout=-1, flags=0) at prov/verbs/src/verbs_eq.c:1008
#3  0x00007ffff7a8200b in fi_eq_sread (eq=0x6647d0, event=0x7ffff56dbe68, buf=0x7ffff56dbea8, len=40, timeout=-1,
    flags=0) at ./include/rdma/fi_eq.h:372
#4  0x00007ffff7a856a1 in rxm_eq_sread (rxm_ep=0x67e820, len=40, entry=0x7ffff56dbe60)
    at prov/rxm/src/rxm_conn.c:1307
#5  0x00007ffff7a85893 in rxm_conn_progress (arg=0x67e820) at prov/rxm/src/rxm_conn.c:1358
#6  0x00007ffff6f70dc5 in start_thread () from /lib64/libpthread.so.0
#7  0x00007ffff6a9b73d in clone () from /lib64/libc.so.6
```

**Comment by shefty** [comment]
This is likely related to commit df435c92
