### ISSUE TITLE
prov/psm2: segfault during shutdown when using the nameserver

### ISSUE THREAD

**Issue by yulujia** [ofiwg/libfabric#5527]
using this commit: 86340704a  
my test segfaults with this back trace:
```
>>> bt
#0  0x0000000000001000 in ?? ()
#1  0x00007f3f75ee22d6 in psm2_mq_test2 () from /lib64/libpsm2.so.2
#2  0x00007f3f766152d0 in psmx2_cq_poll_mq (cq=cq@entry=0x0, trx_ctxt=trx_ctxt@entry=0x1cedd10, event_in=event_in@entry=0x0, count=count@entry=0, src_addr=src_addr@entry=0x0) at prov/psm2/src/psmx2_cq.c:1076
#3  0x00007f3f76612fca in psmx2_progress (trx_ctxt=0x1cedd10) at prov/psm2/src/psmx2.h:1190
#4  psmx2_progress_all (domain=0x1cebbc0) at prov/psm2/src/psmx2.h:1205
#5  psmx2_progress_func (args=0x1cebbc0) at prov/psm2/src/psmx2_domain.c:130
#6  0x00007f3f78b16e25 in start_thread () from /lib64/libpthread.so.0
#7  0x00007f3f77b0d34d in clone () from /lib64/libc.so.6
```
the test uses the ofi+psm2 provider, uses the nameserver to resolve addresses. I launched 8 processes on one node using orterun, each process creates 8 basic endpoints. The test sometimes runs to completion successfully, then during shutdown some processes (usually 2 out of 8) hits this segfault.  Other times the test shuts down cleanly, no problem whatsoever.

**Comment by j-xiong** [comment]
Could you provide a reproducer?
