### ISSUE TITLE
fi_av_insertsvc hangs with UDP;ofi_rxd

### ISSUE THREAD

**Issue by hhirtz** [ofiwg/libfabric#5591]
Hi, if I understand correctly `fi_av_insertsvc`[(1)] inserts a network address from a node+service (e.g. IP address + UDP port) by performing a lookup. However it hangs when I use it, the bound event queue doesn't receive any event.

Example: https://gist.github.com/hhirtz/a6da413262a0819207927948566a4c99
If compiled with `-DUSESVC` (to use `fi_av_insertsvc` instead of `fi_av_insert` with a `struct sockaddr_in`), the client can't lookup the server address.

[(1)]: https://github.com/ofiwg/libfabric/blob/master/man/fi_av.3.md#fi_av_insertsvc

**Comment by hhirtz** [comment]
When the address vector isn't bound to an event queue, the example with `fi_av_insertsvc` segfaults, but works fine with `fi_av_insert`:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b12361 in ofi_bufpool_get_ibuf (index=<optimized out>, pool=0x60e1f0) at ./include/ofi_mem.h:426
426		buf = pool->region_table[(size_t)(index / pool->attr.chunk_cnt)]->
Missing separate debuginfos, use: debuginfo-install glibc-2.17-292.el7.x86_64 libatomic-4.8.5-39.el7.x86_64 libibverbs-22.1-3.el7.x86_64 libnl-1.1.4-3.el7.x86_64 libnl3-3.2.28-4.el7.x86_64 librdmacm-22.1-3.el7.x86_64
(gdb) bt
#0  0x00007ffff7b12361 in ofi_bufpool_get_ibuf (index=<optimized out>, pool=0x60e1f0) at ./include/ofi_mem.h:426
#1  ofi_av_get_addr (av=0x60dc00, fi_addr=<optimized out>) at prov/util/src/util_av.c:247
#2  0x00007ffff7b3c978 in udpx_send (ep_fid=0x6153e0, buf=0x7ffff5ea16d0, len=23, desc=<optimized out>, dest_addr=<optimized out>, context=0x7ffff5ea1690) at prov/udp/src/udpx_ep.c:420
#3  0x00007ffff7b8445d in fi_send (context=0x7ffff5ea1690, dest_addr=<optimized out>, desc=<optimized out>, len=<optimized out>, buf=0x7ffff5ea16d0, ep=<optimized out>)
    at ./include/rdma/fi_endpoint.h:291
#4  rxd_ep_send_pkt (ep=ep@entry=0x7ffff7fce010, pkt_entry=0x7ffff5ea1660) at prov/rxd/src/rxd_ep.c:420
#5  0x00007ffff7b812e7 in rxd_start_xfer (ep=ep@entry=0x7ffff7fce010, tx_entry=tx_entry@entry=ofi_bufpool_get_ibuf0x7ffff6036150) at prov/rxd/src/rxd_cq.c:254
#6  0x00007ffff7b86521 in rxd_ep_generic_sendmsg (rxd_ep=0x7ffff7fce010, iov=<optimized out>, iov_count=1, addr=<optimized out>, tag=<optimized out>, data=<optimized out>, context=0x0, 
    op=0, rxd_flags=0) at prov/rxd/src/rxd_msg.c:415
#7  0x00007ffff7b8667c in rxd_ep_send (ep_fid=<optimized out>, buf=<optimized out>, len=<optimized out>, desc=<optimized out>, dest_addr=<optimized out>, context=<optimized out>)
    at prov/rxd/src/rxd_msg.c:462
#8  0x0000000000400e83 in fi_send (ep=0x7ffff7fce010, buf=0x401cb9, len=7, desc=0x0, dest_addr=0, context=0x0) at /usr/include/rdma/fi_endpoint.h:291
#9  0x0000000000401973 in main_client (dst_addr=0x7fffffffd4b7 "127.0.0.1") at simple.c:310
#10 0x0000000000401a13 in main (argc=2, argv=0x7fffffffd018) at simple.c:334
(gdb) info locals
buf = <optimized out>
(gdb) p *pool
$1 = {free_list = {entries = {head = 0x60e1f0, tail = 0x60e1f0}, regions = {next = 0x60e1f0, prev = 0x60e1f0}}, entry_size = 112, entry_cnt = 0, region_table = 0x0, region_cnt = 0, 
  alloc_size = 114800, region_size = 114688, attr = {size = 80, alignment = 16, max_cnt = 0, chunk_cnt = 1024, alloc_fn = 0x0, free_fn = 0x0, init_fn = 0x0, context = 0x0, flags = 6}}
```

`ofi_bufpool_get_ibuf` tries to dereference `poll->region_table` but it's null.

**Comment by shefty** [comment]
I'm not sure why the API call matters, but thanks for the report.  We'll have to look into this.
