### ISSUE TITLE
[EFA provider] Unable to write to EQ: Missing or unavailable event queue.

### ISSUE THREAD

**Issue by indhub** [ofiwg/libfabric#6249]
I get the following error when calling `fi_cq_read` on the EFA provider. 

I don't see this error when the processes communicating are running on different ec2 instances. I only see this when the processes communicating run on the same ec2 instance.

```
Unable to write to EQ: Missing or unavailable event queue. err: Input/output error (5) prov_errno: Unknown error -12 (-12) prov/efa/src/rxr/rxr.h:1343
```

The process crashes after throwing the above error. Here is stack trace from the crash dump:

```
(gdb) bt
#0  0x00007f0f8d981ae0 in raise () from /lib64/libc.so.6
#1  0x00007f0f8d982f88 in abort () from /lib64/libc.so.6
#2  0x00007f0f8e5c03d2 in rxr_cq_handle_cq_error () from /opt/amazon/efa/lib64/libfabric.so.1
#3  0x00007f0f8e5c7be3 in rxr_ep_progress_internal () from /opt/amazon/efa/lib64/libfabric.so.1
#4  0x00007f0f8e5c9010 in rxr_ep_progress () from /opt/amazon/efa/lib64/libfabric.so.1
#5  0x00007f0f8e58c935 in ofi_cq_progress () from /opt/amazon/efa/lib64/libfabric.so.1
#6  0x00007f0f8e58bd4e in ofi_cq_readfrom () from /opt/amazon/efa/lib64/libfabric.so.1
#7  0x000000000040984b in fi_cq_read (cq=0x251d400, buf=0x7f0f683a6d30, count=1) at /opt/amazon/efa/include/rdma/fi_eq.h:385
#8  0x000000000040a906 in EFA::completionThreadFn (this=0x7ffc6e715b38) at /fsx/herring/commoncpu/EFA.cpp:168
```

Versions:
```
$ cat /opt/amazon/efa_installed_packages 
# EFA installer version: 1.8.3
# Debug packages installed: no
# Packages installed:
efa-1.5.1-1.amzn2.x86_64 ibacm-25.0-1.amzn2.x86_64 infiniband-diags-25.0-1.amzn2.x86_64 infiniband-diags-compat-25.0-1.amzn2.x86_64 libfabric-aws-1.9.0amzn1.1-1.amzn2.x86_64 libfabric-aws-devel-1.9.0amzn1.1-1.amzn2.x86_64 libibumad-25.0-1.amzn2.x86_64 libibverbs-25.0-1.amzn2.x86_64 libibverbs-utils-25.0-1.amzn2.x86_64 librdmacm-25.0-1.amzn2.x86_64 librdmacm-utils-25.0-1.amzn2.x86_64 openmpi40-aws-4.0.2-1.amzn2.x86_64 rdma-core-25.0-1.amzn2.x86_64 rdma-core-devel-25.0-1.amzn2.x86_64
```

Has anyone encountered this issue?

**Comment by wzamazon** [comment]
Offline chat with @indhub, upgrade to latest version of libfabric fixed his issue.
