### ISSUE TITLE
socket provider segfault

### ISSUE THREAD

**Issue by Honggang-LI** [ofiwg/libfabric#6489]
```
[root@rdma-qe-06 coredump]$ file core*
core.fi_bw.0.0977541664914b73aad42fd557a8ed57.70754.1608266669000000:           ELF 64-bit LSB core file, x86-64, version 1 (SYSV), SVR4-style, from 'fi_bw -e msg -v -T 1 -p sockets -s 172.31.1.6', real uid: 0, effective uid: 0, real gid: 0, effective gid: 0, execfn: '/usr/bin/fi_bw', platform: 'x86_64'

core.fi_inj_complete.0.0977541664914b73aad42fd557a8ed57.66147.1608266530000000: ELF 64-bit LSB core file, x86-64, version 1 (SYSV), SVR4-style, from 'fi_inj_complete -e msg -SR -p sockets -s 172.31.1.6', real uid: 0, effective uid: 0, real gid: 0, effective gid: 0, execfn: '/usr/bin/fi_inj_complete', platform: 'x86_64'

core.fi_poll.0.0977541664914b73aad42fd557a8ed57.79655.1608266909000000:         ELF 64-bit LSB core file, x86-64, version 1 (SYSV), SVR4-style, from 'fi_poll -t counter -p tcp;ofi_rxm -s 172.31.1.6', real uid: 0, effective uid: 0, real gid: 0, effective gid: 0, execfn: '/usr/bin/fi_poll', platform: 'x86_64'

core.fi_rma_bw.0.0977541664914b73aad42fd557a8ed57.73041.1608266734000000:       ELF 64-bit LSB core file, x86-64, version 1 (SYSV), SVR4-style, from 'fi_rma_bw -e msg -o write -I 5 -p sockets -s 172.31.1.6', real uid: 0, effective uid: 0, real gid: 0, effective gid: 0, execfn: '/usr/bin/fi_rma_bw', platform: 'x86_64'

[root@rdma-qe-06 coredump]$ gdb -q /usr/bin/fi_bw core.fi_bw.0.0977541664914b73aad42fd557a8ed57.70754.1608266669000000
Reading symbols from /usr/bin/fi_bw...Reading symbols from /usr/lib/debug/usr/bin/fi_bw-1.11.2-1.el8.x86_64.debug...done.
done.
[New LWP 70800]
[New LWP 70754]
[New LWP 70804]
[New LWP 70805]
[New LWP 70801]
[New LWP 70806]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `fi_bw -e msg -v -T 1 -p sockets -s 172.31.1.6'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  sock_ep_cm_shutdown_report (ep=0x0, send_shutdown=send_shutdown@entry=0) at prov/sockets/src/sock_ep_msg.c:282
282		struct fi_eq_cm_entry cm_entry = {0};
[Current thread is 1 (Thread 0x150ad7819700 (LWP 70800))]
Missing separate debuginfos, use: yum debuginfo-install glibc-2.28-141.el8.x86_64 libibverbs-32.0-2.el8.x86_64 libnl3-3.5.0-1.el8.x86_64 libpsm2-11.2.185-1.el8.x86_64 librdmacm-32.0-2.el8.x86_64 numactl-libs-2.0.12-11.el8.x86_64
(gdb) bt
#0  sock_ep_cm_shutdown_report (ep=0x0, send_shutdown=send_shutdown@entry=0) at prov/sockets/src/sock_ep_msg.c:282
#1  0x0000150ada85393e in sock_ep_cm_handle_rx (handle=0x150ad0000d50, cm_head=0x563453235400) at prov/sockets/src/sock_ep_msg.c:1136
#2  sock_ep_cm_thread (arg=0x563453235400) at prov/sockets/src/sock_ep_msg.c:1206
#3  0x0000150ad92d114a in start_thread () from /lib64/libpthread.so.0
#4  0x0000150ada543763 in clone () from /lib64/libc.so.6
(gdb) q



[root@rdma-qe-06 coredump]$ gdb -q /usr/bin/fi_inj_complete core.fi_inj_complete.0.0977541664914b73aad42fd557a8ed57.66147.1608266530000000
Reading symbols from /usr/bin/fi_inj_complete...Reading symbols from /usr/lib/debug/usr/bin/fi_inj_complete-1.11.2-1.el8.x86_64.debug...done.
done.
[New LWP 66251]
[New LWP 66252]
[New LWP 66259]
[New LWP 66147]
[New LWP 66258]
[New LWP 66260]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `fi_inj_complete -e msg -SR -p sockets -s 172.31.1.6'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000014912a9fedea in sock_ep_cm_report_connect_fail (ep=0x0, param=0x0, paramlen=0) at prov/sockets/src/sock_ep_msg.c:348
348	{
[Current thread is 1 (Thread 0x1491279c5700 (LWP 66251))]
Missing separate debuginfos, use: yum debuginfo-install glibc-2.28-141.el8.x86_64 libibverbs-32.0-2.el8.x86_64 libnl3-3.5.0-1.el8.x86_64 libpsm2-11.2.185-1.el8.x86_64 librdmacm-32.0-2.el8.x86_64 numactl-libs-2.0.12-11.el8.x86_64
(gdb) bt
#0  0x000014912a9fedea in sock_ep_cm_report_connect_fail (ep=0x0, param=0x0, paramlen=0) at prov/sockets/src/sock_ep_msg.c:348
#1  0x000014912a9ffcd7 in sock_ep_cm_connect_handler (handle=0x149120000d50, hdr=0x1491279c4da8, cm_head=0x55e6600e9400) at prov/sockets/src/sock_ep_msg.c:400
#2  sock_ep_cm_handle_rx (handle=0x149120000d50, cm_head=0x55e6600e9400) at prov/sockets/src/sock_ep_msg.c:1149
#3  sock_ep_cm_thread (arg=0x55e6600e9400) at prov/sockets/src/sock_ep_msg.c:1206
#4  0x000014912947d14a in start_thread () from /lib64/libpthread.so.0
#5  0x000014912a6ef763 in clone () from /lib64/libc.so.6
(gdb) q



[root@rdma-qe-06 coredump]$ gdb -q /usr/bin/fi_rma_bw core.fi_rma_bw.0.0977541664914b73aad42fd557a8ed57.73041.1608266734000000 
Reading symbols from /usr/bin/fi_rma_bw...Reading symbols from /usr/lib/debug/usr/bin/fi_rma_bw-1.11.2-1.el8.x86_64.debug...done.
done.
[New LWP 73087]
[New LWP 73041]
[New LWP 73088]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `fi_rma_bw -e msg -o write -I 5 -p sockets -s 172.31.1.6'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  sock_ep_cm_shutdown_report (ep=0x0, send_shutdown=send_shutdown@entry=0) at prov/sockets/src/sock_ep_msg.c:282
282		struct fi_eq_cm_entry cm_entry = {0};
[Current thread is 1 (Thread 0x14705b3f2700 (LWP 73087))]
Missing separate debuginfos, use: yum debuginfo-install glibc-2.28-141.el8.x86_64 libibverbs-32.0-2.el8.x86_64 libnl3-3.5.0-1.el8.x86_64 libpsm2-11.2.185-1.el8.x86_64 librdmacm-32.0-2.el8.x86_64 numactl-libs-2.0.12-11.el8.x86_64
(gdb) bt
#0  sock_ep_cm_shutdown_report (ep=0x0, send_shutdown=send_shutdown@entry=0) at prov/sockets/src/sock_ep_msg.c:282
#1  0x000014705e42c93e in sock_ep_cm_handle_rx (handle=0x147054000b60, cm_head=0x55dbd1e49400) at prov/sockets/src/sock_ep_msg.c:1136
#2  sock_ep_cm_thread (arg=0x55dbd1e49400) at prov/sockets/src/sock_ep_msg.c:1206
#3  0x000014705ceaa14a in start_thread () from /lib64/libpthread.so.0
#4  0x000014705e11c763 in clone () from /lib64/libc.so.6


```

**Comment by shefty** [comment]
Socket provider is considered deprecated with no additional development work being added to it.  Third party fixes would be accepted, but no other investment is being made.  This may have been fixed by #6587
