### ISSUE TITLE
`fi_rdm` test hang with shm provider with multi clients

### ISSUE THREAD

**Issue by shijin-aws** [ofiwg/libfabric#6794]
When working on adding the `fi_rdm_multi_client` test in fabtests https://github.com/ofiwg/libfabric/pull/6752, I find this test hangs with shm provider when the second client joins and exchange address with the server during `ft_init_av`. I could reproduce this issue with the current `fi_rdm` test in `fabtests/functional/rdm.c`, which should also be able to handle multi client case as well by specifying the `-C` option in it:

```
# server side cmd:
[ec2-user@ip-172-31-12-16 ~] fi_rdm -p shm -C 2 -s 127.0.0.1
# client side cmd:
# (first client succeeds)
[ec2-user@ip-172-31-12-16 ~]$ fi_rdm -p shm -s 127.0.0.1 127.0.0.1
Sending message...
Send completion received
# second client hangs: 
[ec2-user@ip-172-31-12-16 ~]$ fi_rdm -p shm -s 127.0.0.1 127.0.0.1
(hang)
```

Stack trace for the hang in client side:

```
(gdb) bt
#0  0x00007f29d4a170e3 in pthread_spin_lock () from /lib64/libpthread.so.0
#1  0x00007f29d5722236 in smr_verify_peer ()
   from /fsx/libfabric/install/lib/libfabric.so.1
#2  0x00007f29d571df4d in smr_generic_sendmsg ()
   from /fsx/libfabric/install/lib/libfabric.so.1
#3  0x00007f29d571e5c6 in smr_send ()
   from /fsx/libfabric/install/lib/libfabric.so.1
#4  0x0000000000404024 in fi_send (context=0x60f7a0 <tx_ctx>, dest_addr=0,
    desc=0x0, len=17, buf=0x7f29d5b6c010, ep=0x11472c0)
    at /fsx/libfabric/install/include/rdma/fi_endpoint.h:291
#5  ft_post_tx_buf (ep=ep@entry=0x11472c0, fi_addr=fi_addr@entry=0,
    size=size@entry=17, data=data@entry=0, ctx=ctx@entry=0x60f7a0 <tx_ctx>,
    op_buf=0x7f29d5b6c010, op_mr_desc=0x0, op_tag=0) at common/shared.c:1908
#6  0x00000000004041b5 in ft_post_tx (ep=ep@entry=0x11472c0,
    fi_addr=fi_addr@entry=0, size=size@entry=17, data=data@entry=0,
    ctx=ctx@entry=0x60f7a0 <tx_ctx>) at common/shared.c:1919
#7  0x00000000004076b5 in ft_tx (ep=0x11472c0, fi_addr=0, size=17,
    ctx=0x60f7a0 <tx_ctx>) at common/shared.c:1930
#8  0x000000000040953c in ft_init_av_dst_addr (av_ptr=<optimized out>,
    ep_ptr=0x11472c0, remote_addr=remote_addr@entry=0x60f590 <remote_fi_addr>)
    at common/shared.c:1331
#9  0x00000000004095d0 in ft_init_av () at common/shared.c:1272
#10 0x00000000004096b7 in ft_init_fabric () at common/shared.c:1108
#11 0x0000000000401627 in run () at functional/rdm.c:43
```

on server side:

```
#0  0x00007fad7c009d03 in smr_ep_progress ()
   from /fsx/libfabric/install/lib/libfabric.so.1
#1  0x00007fad7bf8a1f5 in ofi_cq_progress ()
   from /fsx/libfabric/install/lib/libfabric.so.1
#2  0x00007fad7bf896f6 in ofi_cq_readfrom ()
   from /fsx/libfabric/install/lib/libfabric.so.1
#3  0x00000000004052c6 in fi_cq_read (count=1, buf=0x7ffc749de2b0, cq=0x888340)
    at /fsx/libfabric/install/include/rdma/fi_eq.h:394
#4  ft_spin_for_comp (timeout=-1, total=3, cur=0x60f800 <rx_cq_cntr>, cq=0x888340)
    at common/shared.c:2232
#5  ft_get_cq_comp (cq=0x888340, cur=0x60f800 <rx_cq_cntr>, total=3, timeout=-1)
    at common/shared.c:2324
#6  0x00000000004093fa in ft_init_av_dst_addr (av_ptr=0x896420, ep_ptr=0x8a7e40,
    remote_addr=remote_addr@entry=0x60f590 <remote_fi_addr>)
    at common/shared.c:1339
#7  0x00000000004095d0 in ft_init_av () at common/shared.c:1272
#8  0x0000000000409618 in ft_accept_next_client () at common/shared.c:784
#9  0x0000000000401661 in run () at functional/rdm.c:54
```

The current `runfabtests.sh` has `fi_rdm` without specifying `-C`: https://github.com/ofiwg/libfabric/blob/master/fabtests/scripts/runfabtests.sh#L111,  so it uses the default client number (1) and this issue is not exposed.

**Comment by j-xiong** [comment]
fixed by #6847
