### ISSUE TITLE
prov/sockets: possible SEGV after cmap realloc due to dangling conn reference

### ISSUE THREAD

**Issue by bfaccini** [ofiwg/libfabric#7520]
**Describe the bug**
During IOR-easy testing with 16 client nodes each running 64 tasks/node, with `libfabric 1.14` and using `sockets` provider, a DAOS Server/engine has crashed due to a SEGV.

**To Reproduce**
Looks like this occurs when running with a number of client tasks likely to get the cmap table default size (1024) to be quickly exceed and thus require it to be dynamically expanded/realloc()'ed.

Attempts are presently being run in order to confirm this and also that forcing a new/bigger-enough cmap table size upon start (`def_conn_map_sz`) will fix ...

**Expected behavior**
The current feature designed to allow dynamic cmap expand needs to be strengthened.

**Output**
The SEGV backtrace is as follow : 
```
#0  0x00007efc62716113 in sock_pe_process_rx_conn_msg (pe=0x7efc30231650, rx_ctx=0x7efc30231650, pe_entry=0x7efc30240670) at prov/sockets/src/sock_progress.c:1497
#1  sock_pe_process_recv (pe_entry=0x7efc30240670, rx_ctx=0x7efc30231650, pe=0x7efc30231650) at prov/sockets/src/sock_progress.c:1567
#2  sock_pe_progress_rx_pe_entry (pe=pe@entry=0x7efc30231650, pe_entry=0x7efc30240670, rx_ctx=rx_ctx@entry=0x7efb6c051160) at prov/sockets/src/sock_progress.c:2058
#3  0x00007efc62718ac5 in sock_pe_progress_rx_ctx (pe=pe@entry=0x7efc30231650, rx_ctx=rx_ctx@entry=0x7efb6c051160) at prov/sockets/src/sock_progress.c:2449
#4  0x00007efc6271a0e0 in sock_pe_progress_thread (data=0x7efc30231650) at prov/sockets/src/sock_progress.c:2668
#5  0x00007efc68fd217a in start_thread () from /lib64/libpthread.so.0
#6  0x00007efc681fddc3 in clone () from /lib64/libc.so.6

```

here is the concerned sock_pe_entry : 
```
$16 = {pe = {tx = {tx_op = {op = 0x0, src_iov_len = 0x0, dest_iov_len = 0x0, atomic = {op = 0x0, datatype = 0x0, res_iov_len = 0x0, cmp_iov_len = 0x0}, reserved = {0x0}}, 
      comp = 0x0, header_sent = 0x1, send_done = 0x0, reserved = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, tx_ctx = 0x0, tx_iov = {{src = {iov = {addr = 0x0, len = 0x0, key = 0x0}, ioc = {
              addr = 0x0, count = 0x0, key = 0x0}}, dst = {iov = {addr = 0x0, len = 0x0, key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}, res = {iov = {addr = 0x0, 
              len = 0x0, key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}, cmp = {iov = {addr = 0x0, len = 0x0, key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}}, {
          src = {iov = {addr = 0x0, len = 0x0, key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}, dst = {iov = {addr = 0x0, len = 0x0, key = 0x0}, ioc = {addr = 0x0, 
              count = 0x0, key = 0x0}}, res = {iov = {addr = 0x0, len = 0x0, key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}, cmp = {iov = {addr = 0x0, len = 0x0, 
              key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}}, {src = {iov = {addr = 0x0, len = 0x0, key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}, dst = {iov = {
              addr = 0x0, len = 0x0, key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}, res = {iov = {addr = 0x0, len = 0x0, key = 0x0}, ioc = {addr = 0x0, count = 0x0, 
              key = 0x0}}, cmp = {iov = {addr = 0x0, len = 0x0, key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}}, {src = {iov = {addr = 0x0, len = 0x0, key = 0x0}, ioc = {
              addr = 0x0, count = 0x0, key = 0x0}}, dst = {iov = {addr = 0x0, len = 0x0, key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}, res = {iov = {addr = 0x0, 
              len = 0x0, key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}, cmp = {iov = {addr = 0x0, len = 0x0, key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}}, {
          src = {iov = {addr = 0x0, len = 0x0, key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}, dst = {iov = {addr = 0x0, len = 0x0, key = 0x0}, ioc = {addr = 0x0, 
              count = 0x0, key = 0x0}}, res = {iov = {addr = 0x0, len = 0x0, key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}, cmp = {iov = {addr = 0x0, len = 0x0, 
              key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}}, {src = {iov = {addr = 0x0, len = 0x0, key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}, dst = {iov = {
              addr = 0x0, len = 0x0, key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}, res = {iov = {addr = 0x0, len = 0x0, key = 0x0}, ioc = {addr = 0x0, count = 0x0, 
              key = 0x0}}, cmp = {iov = {addr = 0x0, len = 0x0, key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}}, {src = {iov = {addr = 0x0, len = 0x0, key = 0x0}, ioc = {
              addr = 0x0, count = 0x0, key = 0x0}}, dst = {iov = {addr = 0x0, len = 0x0, key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}, res = {iov = {addr = 0x0, 
              len = 0x0, key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}, cmp = {iov = {addr = 0x0, len = 0x0, key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}}, {
          src = {iov = {addr = 0x0, len = 0x0, key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}, dst = {iov = {addr = 0x0, len = 0x0, key = 0x0}, ioc = {addr = 0x0, 
              count = 0x0, key = 0x0}}, res = {iov = {addr = 0x0, len = 0x0, key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}, cmp = {iov = {addr = 0x0, len = 0x0, 
              key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}}}, inject = {0x0 <repeats 255 times>}}, rx = {rx_op = {op = 0x0, src_iov_len = 0x0, dest_iov_len = 0x0, 
        atomic = {op = 0x0, datatype = 0x0, res_iov_len = 0x0, cmp_iov_len = 0x0}, reserved = {0x0}}, comp = 0x0, header_read = 0x1, pending_send = 0x0, reserved = {0x0, 0x0, 0x0, 
        0x0, 0x0, 0x0}, rx_entry = 0x0, rx_iov = {{iov = {addr = 0x0, len = 0x0, key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}, {iov = {addr = 0x0, len = 0x0, key = 0x0}, 
          ioc = {addr = 0x0, count = 0x0, key = 0x0}}, {iov = {addr = 0x0, len = 0x0, key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}, {iov = {addr = 0x0, len = 0x0, 
            key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}, {iov = {addr = 0x0, len = 0x0, key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}, {iov = {addr = 0x0, 
            len = 0x0, key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}, {iov = {addr = 0x0, len = 0x0, key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}, {iov = {
            addr = 0x0, len = 0x0, key = 0x0}, ioc = {addr = 0x0, count = 0x0, key = 0x0}}}, atomic_cmp = 0x0, atomic_src = 0x0}}, msg_hdr = {version = 0x2, op_type = 0xc, 
    rx_id = 0x0, dest_iov_len = 0x0, pe_entry_id = 0x7f, reserved = {0x0, 0x0}, flags = 0x0, msg_len = 0x48}, response = {msg_hdr = {version = 0x0, op_type = 0x0, rx_id = 0x0, 
      dest_iov_len = 0x0, pe_entry_id = 0x0, reserved = {0x0, 0x0}, flags = 0x0, msg_len = 0x0}, pe_entry_id = 0x0, err = 0x0, reserved = {0x0, 0x0}}, flags = 0x0, context = 0x0, 
  addr = 0x0, data = 0x0, tag = 0x0, buf = 0x0, type = 0x0, is_complete = 0x0, is_error = 0x0, mr_checked = 0x0, is_pool_entry = 0x0, completion_reported = 0x0, reserved = {0x0, 
    0x0, 0x0}, done_len = 0x48, total_len = 0x48, data_len = 0x0, rem = 0x0, comm_addr = 0x7efa98000d20, ep_attr = 0x7efb6c051890, 
conn = 0x7efb6c09f1a0,  
                  |-> struct sock_conn

comp = 0x7efb6c0511e8, entry = {next = 0x7efc30246940, prev = 0x7efc3024ad18}, ctx_entry = {next = 0x7efc30246950, prev = 0x7efb6c051280}, comm_buf = {size = 0x400, size_mask = 0x3ff, rcnt = 0x48, 
    wcnt = 0x48, wpos = 0x48, buf = 0x7efc30182b30}, cache_sz = 0x400}

```
here is the associated sock_conn : 
```
$11 = {sock_fd = 0x0, connected = 0x1, address_published = 0x0, addr = {sa = {sa_family = 0x2, sa_data = {0x8a, 0xcb, 0xac, 0x1e, 0x3e, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 
        0x0}}, sin = {sin_family = 0x2, sin_port = 0xcb8a, sin_addr = {s_addr = 0xa3e1eac}, sin_zero = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}}, sin6 = {sin6_family = 0x2, 
      sin6_port = 0xcb8a, sin6_flowinfo = 0xa3e1eac, sin6_addr = {__in6_u = {__u6_addr8 = {0x0 <repeats 16 times>}, __u6_addr16 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, 
          __u6_addr32 = {0x0, 0x0, 0x0, 0x0}}}, sin6_scope_id = 0x0}, sib = {sib_family = 0x2, sib_pkey = 0xcb8a, sib_flowinfo = 0xa3e1eac, sib_addr = {0x0 <repeats 16 times>}, 
      sib_sid = 0x0, sib_sid_mask = 0x0, sib_scope_id = 0x0}, align = {0x2, 0x0, 0x8a, 0xcb, 0xac, 0x1e, 0x3e, 0xa, 0x0 <repeats 40 times>}}, rx_pe_entry = 0x7efc30240670, 
  tx_pe_entry = 0x0, 
ep_attr = 0x0, 
     |-> == NULL
av_index = 0x0, ep_entry = {next = 0x0, prev = 0x0}}
```
and here is where the SEGV has occurred due to the pe_entry->conn->ep_attr pointer being NULL : 
```
static int sock_pe_process_rx_conn_msg(struct sock_pe *pe,
                                        struct sock_rx_ctx *rx_ctx,
                                        struct sock_pe_entry *pe_entry)
{
        uint64_t len, data_len;
        struct sock_ep_attr *ep_attr;
        struct sock_conn_map *map;
        union ofi_sock_ip *addr;
        struct sock_conn *conn;
        uint64_t index;

        if (!pe_entry->comm_addr) {
                pe_entry->comm_addr = calloc(1, sizeof(union ofi_sock_ip));
                if (!pe_entry->comm_addr)
                        return -FI_ENOMEM;
        }

        len = sizeof(struct sock_msg_hdr);
        data_len = sizeof(union ofi_sock_ip);
        if (sock_pe_recv_field(pe_entry, pe_entry->comm_addr, data_len, len)) {
                return 0;
        }

        ep_attr = pe_entry->conn->ep_attr;    <<<<<<<<<<<<<<
        map = &ep_attr->cmap;
        addr = pe_entry->comm_addr;
        pe_entry->conn->addr = *addr;

        index = (ep_attr->ep_type == FI_EP_MSG) ? 0 : sock_av_get_addr_index(ep_attr->av, addr);
                             |-> SEGV !!!
………………………

```
but if we access the sock_ep_attr by using directly its pointer in the sock_pe_entry : 
```
$24 = {fclass = 0x3, tx_shared = 0x0, rx_shared = 0x0, buffered_len = 0x0, min_multi_recv = 0x40, ref = {val = 0x0}, eq = 0x0, av = 0x7efc30226f30, domain = 0x7efc3022d8c0, 
  rx_ctx = 0x7efb6c051160, tx_ctx = 0x7efb6c050dd0, rx_array = 0x7efb6c04fa80, tx_array = 0x7efb6c04fd80, num_rx_ctx = {val = 0x0}, num_tx_ctx = {val = 0x0}, rx_ctx_entry = {
    next = 0x7efb6c0512b0, prev = 0x7efb6c0512b0}, tx_ctx_entry = {next = 0x7efb6c050f20, prev = 0x7efb6c050f20}, info = {next = 0x0, caps = 0xb38000000313f0c, mode = 0x0, 
    addr_format = 0x2, src_addrlen = 0x10, dest_addrlen = 0x0, src_addr = 0x7efb6c050040, dest_addr = 0x0, handle = 0x0, tx_attr = 0x7efb6c04fe20, rx_attr = 0x7efb6c04fe80, 
    ep_attr = 0x7efb6c04fed0, domain_attr = 0x7efb6c04ff40, fabric_attr = 0x7efb6c050060, nic = 0x0}, ep_attr = {type = 0x0, protocol = 0x0, protocol_version = 0x0, 
    max_msg_size = 0x0, msg_prefix_size = 0x0, max_order_raw_size = 0x0, max_order_war_size = 0x0, max_order_waw_size = 0x0, mem_tag_format = 0x0, tx_ctx_cnt = 0x1, 
    rx_ctx_cnt = 0x1, auth_key_size = 0x0, auth_key = 0x0}, ep_type = 0x3, src_addr = 0x7efb6c04fa40, dest_addr = 0x0, msg_src_port = 0x7ac5, msg_dest_port = 0x0, peer_fid = 0x0, 
  key = 0x0, is_enabled = 0x1, cm = {sock = 0x0, lock = 0x1, state = 0x0}, conn_handle = {sock = 0x818, do_listen = 0x1}, lock = 0x1, av_idm = {array = {0x7efb6c0a21c0, 
      0x0 <repeats 1023 times>}, count = {0x2, 0x0 <repeats 1023 times>}}, cmap = {table = 0x7eee7c7b1bf0, epoll_set = 0x773, epoll_events = 0x7efb6e45e660, epoll_size = 0x802, 
    used = 0x402, <<<<<<<<<<
size = 0x800, 
    |-> == 2048
lock = 0x1}}
```
we can see that the size of its cmap table is twice the default/init size (1024/`sock_cm_def_map_sz`), meaning it has been expanded, and since the `used` value is still very close to the original one, it is likely that this should have just happened.

Then looking to the code where the sock_conn struct dereferences occur I have strong assumption that a cmap table realloc() may easily cause a SEGV if some sock_conn struct previous address could be reused after the expand (and possible relocation), like the ones that are stored in the epoll_event structs during the polling of the sockets fds ...

**Environment:**
CentOS Linux release 8.4.2105, libfabric 1.14 with sockets provider, DAOS v2.0.1

**Comment by aakefbs** [comment]
Out of interest, why are you using the sock and not tcp provider?

**Comment by bfaccini** [comment]
> Out of interest, why are you using the sock and not tcp provider?

We have tested both. If reporting bugs against sockets provider are "out of interest", why not simply remove this provider ?

**Comment by aakefbs** [comment]
I'm just asking, from the DDN/IME side we had given up some time on prov/sockets in favor of prov/tcp as we run into too many issues and I simply didn't have time to report all them.

**Comment by bfaccini** [comment]
> from the DDN/IME side we had given up some time on prov/sockets in favor of prov/tcp as we run into too many issues and I simply didn't have time to report all them.

Well, you are probably right then and this may be a waste of time, but let see if people from libfabric find it of interest ;-)

**Comment by shefty** [comment]
There are no developers dedicated to the sockets provider and haven't been in a long time.  It has been deprecated, but not removed because there are users of the sockets provider still.  This is mostly from users who are coding to specific features not supported by the tcp provider path (e.g. scalable endpoints).  The sockets provider attempted to implement all features of the API at the time it was written.  It was meant for development purposes.  However, it turned out that application developers really liked the idea of libfabric working over sockets, but needed a performance focus.  So, the tcp provider has a performance focus.

We are still accepting fixes to the sockets provider.  If there are easy problems to resolve, we can add patches.  But I do not expect any significant developer investing into this provider.

**Comment by chien-intel** [comment]
Closing this issue as there is no interest.
