### ISSUE TITLE
prov/util: memory leaks from cq open 

### ISSUE THREAD

**Issue by soumagne** [ofiwg/libfabric#8534]
`tcp` and `tcp;ofi_rxm` both report memory leaks from CQ open. Note that this is with latest main branch (4ff6e66fd6f2ab23eae3f9e689d88d61e2742eb7)

Here is the trace when using `tcp;ofi_rxm`:
```bash
=================================================================
==245992==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 136 byte(s) in 1 object(s) allocated from:
    #0 0x7fa8b62ba097 in calloc (/lib64/libasan.so.8+0xba097)
    #1 0x7fa8b611e6b6 in ofi_bufpool_create_attr ../prov/util/src/util_buf.c:218
    #2 0x7fa8b616764d in ofi_bufpool_create ../include/ofi_mem.h:403
    #3 0x7fa8b616886c in rxm_ep_create_pools ../prov/rxm/src/rxm_ep.c:282
    #4 0x7fa8b616bdc1 in rxm_ep_txrx_res_open ../prov/rxm/src/rxm_ep.c:1503
    #5 0x7fa8b616c167 in rxm_ep_ctrl ../prov/rxm/src/rxm_ep.c:1585
    #6 0x7fa8b69ea790 in fi_enable /opt/libfabric/git/include/rdma/fi_endpoint.h:216
    #7 0x7fa8b69ea790 in na_ofi_basic_ep_open /home/jsoumagn/workspace/mercury-hpc/mercury/src/na/na_ofi.c:4213
    #8 0x7fa8b69ea790 in na_ofi_endpoint_open /home/jsoumagn/workspace/mercury-hpc/mercury/src/na/na_ofi.c:4143
    #9 0x7fa8b69ea790 in na_ofi_initialize /home/jsoumagn/workspace/mercury-hpc/mercury/src/na/na_ofi.c:6313
    #10 0x7fa8b69a9fae in NA_Initialize_opt /home/jsoumagn/workspace/mercury-hpc/mercury/src/na/na.c:672
    #11 0x40a890 in NA_Test_init /home/jsoumagn/workspace/mercury-hpc/mercury/Testing/common/na_test.c:568
    #12 0x40573a in na_perf_init /home/jsoumagn/workspace/mercury-hpc/mercury/Testing/perf/na/na_perf.c:128
    #13 0x4037b0 in main /home/jsoumagn/workspace/mercury-hpc/mercury/Testing/perf/na/na_perf_server.c:195
    #14 0x7fa8b4e2950f in __libc_start_call_main (/lib64/libc.so.6+0x2950f)

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7fa8b62ba097 in calloc (/lib64/libasan.so.8+0xba097)
    #1 0x7fa8b6114277 in util_init_peer_cq ../prov/util/src/util_cq.c:664
    #2 0x7fa8b6114689 in ofi_cq_init ../prov/util/src/util_cq.c:762
    #3 0x7fa8b61a5740 in xnet_cq_open ../prov/tcp/src/xnet_cq.c:286
    #4 0x7fa8b6166a8a in fi_cq_open ../include/rdma/fi_domain.h:353
    #5 0x7fa8b616b6be in rxm_ep_msg_cq_open ../prov/rxm/src/rxm_ep.c:1368
    #6 0x7fa8b616c0f9 in rxm_ep_ctrl ../prov/rxm/src/rxm_ep.c:1571
    #7 0x7fa8b69ea790 in fi_enable /opt/libfabric/git/include/rdma/fi_endpoint.h:216
    #8 0x7fa8b69ea790 in na_ofi_basic_ep_open /home/jsoumagn/workspace/mercury-hpc/mercury/src/na/na_ofi.c:4213
    #9 0x7fa8b69ea790 in na_ofi_endpoint_open /home/jsoumagn/workspace/mercury-hpc/mercury/src/na/na_ofi.c:4143
    #10 0x7fa8b69ea790 in na_ofi_initialize /home/jsoumagn/workspace/mercury-hpc/mercury/src/na/na_ofi.c:6313
    #11 0x7fa8b69a9fae in NA_Initialize_opt /home/jsoumagn/workspace/mercury-hpc/mercury/src/na/na.c:672
    #12 0x40a890 in NA_Test_init /home/jsoumagn/workspace/mercury-hpc/mercury/Testing/common/na_test.c:568
    #13 0x40573a in na_perf_init /home/jsoumagn/workspace/mercury-hpc/mercury/Testing/perf/na/na_perf.c:128
    #14 0x4037b0 in main /home/jsoumagn/workspace/mercury-hpc/mercury/Testing/perf/na/na_perf_server.c:195
    #15 0x7fa8b4e2950f in __libc_start_call_main (/lib64/libc.so.6+0x2950f)

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7fa8b62ba097 in calloc (/lib64/libasan.so.8+0xba097)
    #1 0x7fa8b6114277 in util_init_peer_cq ../prov/util/src/util_cq.c:664
    #2 0x7fa8b6114689 in ofi_cq_init ../prov/util/src/util_cq.c:762
    #3 0x7fa8b617bb3f in rxm_cq_open ../prov/rxm/src/rxm_cq.c:2135
    #4 0x7fa8b69ce5a3 in fi_cq_open /opt/libfabric/git/include/rdma/fi_domain.h:353
    #5 0x7fa8b69ce5a3 in na_ofi_eq_open /home/jsoumagn/workspace/mercury-hpc/mercury/src/na/na_ofi.c:4387
    #6 0x7fa8b69ea461 in na_ofi_basic_ep_open /home/jsoumagn/workspace/mercury-hpc/mercury/src/na/na_ofi.c:4177
    #7 0x7fa8b69ea461 in na_ofi_endpoint_open /home/jsoumagn/workspace/mercury-hpc/mercury/src/na/na_ofi.c:4143
    #8 0x7fa8b69ea461 in na_ofi_initialize /home/jsoumagn/workspace/mercury-hpc/mercury/src/na/na_ofi.c:6313
    #9 0x7fa8b69a9fae in NA_Initialize_opt /home/jsoumagn/workspace/mercury-hpc/mercury/src/na/na.c:672
    #10 0x40a890 in NA_Test_init /home/jsoumagn/workspace/mercury-hpc/mercury/Testing/common/na_test.c:568
    #11 0x40573a in na_perf_init /home/jsoumagn/workspace/mercury-hpc/mercury/Testing/perf/na/na_perf.c:128
    #12 0x4037b0 in main /home/jsoumagn/workspace/mercury-hpc/mercury/Testing/perf/na/na_perf_server.c:195
    #13 0x7fa8b4e2950f in __libc_start_call_main (/lib64/libc.so.6+0x2950f)

SUMMARY: AddressSanitizer: 200 byte(s) leaked in 3 allocation(s).
```

Similarly when running with `tcp` without `ofi;rxm`:
```bash
==246102==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7fa1fb2ba097 in calloc (/lib64/libasan.so.8+0xba097)
    #1 0x7fa1fb00b277 in util_init_peer_cq ../prov/util/src/util_cq.c:664
    #2 0x7fa1fb00b689 in ofi_cq_init ../prov/util/src/util_cq.c:762
    #3 0x7fa1fb09c740 in xnet_cq_open ../prov/tcp/src/xnet_cq.c:286
    #4 0x7fa1fb15d5a3 in fi_cq_open /opt/libfabric/git/include/rdma/fi_domain.h:353
    #5 0x7fa1fb15d5a3 in na_ofi_eq_open /home/jsoumagn/workspace/mercury-hpc/mercury/src/na/na_ofi.c:4387
    #6 0x7fa1fb179461 in na_ofi_basic_ep_open /home/jsoumagn/workspace/mercury-hpc/mercury/src/na/na_ofi.c:4177
    #7 0x7fa1fb179461 in na_ofi_endpoint_open /home/jsoumagn/workspace/mercury-hpc/mercury/src/na/na_ofi.c:4143
    #8 0x7fa1fb179461 in na_ofi_initialize /home/jsoumagn/workspace/mercury-hpc/mercury/src/na/na_ofi.c:6313
    #9 0x7fa1fb138fae in NA_Initialize_opt /home/jsoumagn/workspace/mercury-hpc/mercury/src/na/na.c:672
    #10 0x40a890 in NA_Test_init /home/jsoumagn/workspace/mercury-hpc/mercury/Testing/common/na_test.c:568
    #11 0x40573a in na_perf_init /home/jsoumagn/workspace/mercury-hpc/mercury/Testing/perf/na/na_perf.c:128
    #12 0x4037b0 in main /home/jsoumagn/workspace/mercury-hpc/mercury/Testing/perf/na/na_perf_server.c:195
    #13 0x7fa1f9c2950f in __libc_start_call_main (/lib64/libc.so.6+0x2950f)

SUMMARY: AddressSanitizer: 32 byte(s) leaked in 1 allocation(s).
```

**Comment by shefty** [comment]
I think this impacts all providers.  I have a fix, verifying then opening a PR.

**Comment by soumagne** [comment]
Confirm that fixes it.

**Comment by shefty** [comment]
thanks!

**Comment by soumagne** [comment]
actually correction :) there is still a leak in rxm, see below:
```
==265760==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 136 byte(s) in 1 object(s) allocated from:
    #0 0x7fb7bbcba097 in calloc (/lib64/libasan.so.8+0xba097)
    #1 0x7fb7bba2f6c9 in ofi_bufpool_create_attr ../prov/util/src/util_buf.c:218
    #2 0x7fb7bba78660 in ofi_bufpool_create ../include/ofi_mem.h:403
    #3 0x7fb7bba7987f in rxm_ep_create_pools ../prov/rxm/src/rxm_ep.c:282
    #4 0x7fb7bba7cdd4 in rxm_ep_txrx_res_open ../prov/rxm/src/rxm_ep.c:1503
    #5 0x7fb7bba7d17a in rxm_ep_ctrl ../prov/rxm/src/rxm_ep.c:1585
    #6 0x7fb7bbb79860 in fi_enable /opt/libfabric/git/include/rdma/fi_endpoint.h:216
    #7 0x7fb7bbb79860 in na_ofi_basic_ep_open /home/jsoumagn/workspace/mercury-hpc/mercury/src/na/na_ofi.c:4220
    #8 0x7fb7bbb79860 in na_ofi_endpoint_open /home/jsoumagn/workspace/mercury-hpc/mercury/src/na/na_ofi.c:4150
    #9 0x7fb7bbb79860 in na_ofi_initialize /home/jsoumagn/workspace/mercury-hpc/mercury/src/na/na_ofi.c:6321
    #10 0x7fb7bbb38fae in NA_Initialize_opt /home/jsoumagn/workspace/mercury-hpc/mercury/src/na/na.c:672
    #11 0x40a890 in NA_Test_init /home/jsoumagn/workspace/mercury-hpc/mercury/Testing/common/na_test.c:568
    #12 0x40573a in na_perf_init /home/jsoumagn/workspace/mercury-hpc/mercury/Testing/perf/na/na_perf.c:128
    #13 0x4037b0 in main /home/jsoumagn/workspace/mercury-hpc/mercury/Testing/perf/na/na_perf_server.c:195
    #14 0x7fb7ba62950f in __libc_start_call_main (/lib64/libc.so.6+0x2950f)

SUMMARY: AddressSanitizer: 136 byte(s) leaked in 1 allocation(s).
```

**Comment by shefty** [comment]
That looks specific to rxm and may be present in branches.  Tracking that as a separate issue.
